<?php
DEFINE("REGIST_FORM","Regisztráció");
DEFINE("SCOPE_FORM","Adat átadás a klien applikációnak");
DEFINE("LOGIN_FORM","Bejelentkezés");
DEFINE('FORGETPSW_FORM','Elfelejtett ejlszó');
DEFINE("PASSWORD","Jelszó");
DEFINE("SCOPE_TO_CLIENT","A kliens a következő adatokat kapja meg");
DEFINE("UKLOGIN_POLICY","uklogin szolgáltatás adatkezelési leírása");
DEFINE("CLIENT_POLICY","Kliens alkalmazás adatkezelési leírása");
DEFINE("ACCEPT_POLICY","Adatkezeléshez hozzájárulok");
DEFINE("FORGET_MY_PASSWORD","Elfelejetettem a jelszavamat");
DEFINE("NO_ACCOUNT_REGIST","Még nincs fiókom, regisztrálok");
DEFINE("sub","Azonoító kód");
DEFINE("nickname","Bejelentkezési név");
DEFINE("postal_code","Postai irányító szám");
DEFINE("locality","Település");
DEFINE("street_addres","utca és házszám");
DEFINE("address","Teljes lakcím");
DEFINE("email","E-mail");
DEFINE("email_verified","E-mail ellenörzött");
DEFINE("given_name","Második kersztnév");
DEFINE("middle_name","Első keresztnév");
DEFINE("family_name","Vezeték név");
DEFINE("name","Teljes név");
DEFINE("picture","Avatar kép URI");
DEFINE("birth_date","Születési dátum");
DEFINE("phone_number","Telefon szám");
DEFINE("phone_number_verified","Telefonszám ellenörzött"); 
DEFINE("updated_at","Utolsó módosítás időpontja");
DEFINE("audited","Hiteles");
DEFINE("auditor","Hitelesítő");
DEFINE("audit_time","Hitelesítés időpontja");
DEFINE("sysadmin","Rendszer adminisztrátor");
DEFINE("NICK_REQUIRED","Bejelentkezési nevet meg kell adni");
DEFINE("EMAIL_REQUIRED","Email címet meg kell adni");
DEFINE("PASSWORDS_NOTEQUALS","A két jelszó nem egyforma");
DEFINE("DATAPROCESS_ACCEPT_REQUIRED","Az adatkezelést el kell fogadni");
DEFINE("PSW_REQUIRED","Jelszót meg kell adni");
DEFINE("INVALID_LOGIN","Hibás bejelentkezés");
DEFINE("NICK_EXISTS","Ez a bejelentkezési név már foglalt");
DEFINE("NICK_NOT_FOUND","Nincs ilyen bejelentkezési név");
DEFINE("NOT_SUUPORTED_SCOPE","Nem támogatott adatkérés");
DEFINE("ENABLED_SCOPE","Támogatott adatkérések");
DEFINE("LBL_PSW4","Jelszó ismét");
DEFINE('SIGN_HASH_EXISTS','Ezzel az ügyfélkapu aláírással már van regisztráció');
DEFINE('NEW_PSW_SENDED','Új jelszó elküldve ');
DEFINE('EMPTY_EMAIL','Nincs e-mail megadva');

?>
